version: '3.8'
services:
  postgres-service:
    container_name: postgresql-db
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
